### ISSUE TITLE
Allow to release a version to trunk

### ISSUE THREAD

**Issue by ocean90** [toolstack/git-to-wp-plugin-dir-release-script#1]
Something like `.release.sh trunk` would be handy to only update the code in trunk.

**Comment by toolstack** [comment]
I was thinking along the same lines, maybe a `release.sh install /path/to/plugin` and `release.sh update`.

The install would create a /bin directory and put the .sh and .template file there, then commit them to git.

The update would grab the most current version from here and commit it.

**Comment by ocean90** [comment]
Sorry I wasn't clear: I meant to update the source on plugin.svn without a SVN tag, instead push the source to trunk.

**Comment by toolstack** [comment]
Ah, ok, yea that makes sense too, should be easy to do as it's really just skipping the tagging at the end.

**Comment by toolstack** [comment]
If there's no SVN tag should it also ignore the git tag?  Aka pull from "master" on the git side instead of a tag?

**Comment by ocean90** [comment]
Maybe make it optional? For GlotPress' pre-releases I create tags on GitHub but not on plugins.svn.

**Comment by toolstack** [comment]
I was trying to avoid getting too fancy with the command line options, I'll have to think about how to handle it.  At the moment the code does support "trunk" as a tag and pulls from "master".

**Comment by toolstack** [comment]
@ocean90 take a look at [this](https://github.com/toolstack/git-to-wp-plugin-dir-release-script/tree/PHP_Based) branch and see what you think.

It's still rough and I haven't tested it much, but I think it's a better way to go.

**Comment by toolstack** [comment]
The current code base can now release to trunk and use other GIT tags as well.
