### ISSUE TITLE
Use new API version for core/version-check

### ISSUE THREAD

**Issue by ocean90** [toolstack/git-to-wp-plugin-dir-release-script#11]
Instead of https://api.wordpress.org/core/version-check/1.6/ you can use https://api.wordpress.org/core/version-check/1.7/ which provides JSON.

**Comment by ocean90** [comment]
There is also https://api.wordpress.org/core/stable-check/1.0/

**Comment by toolstack** [comment]
Any particular reason not to use 1.6?  Is it being deprecated at some point?

**Comment by ocean90** [comment]
I just think that the use of `unserialize()` should be avoided if possible.

**Comment by toolstack** [comment]
I don't see a big difference between an `unserialize()` call and a `json_decode()` call, I'll close this for now and it can be revisited if 1.6 becomes deprecated at some point.

**Comment by ocean90** [comment]
Well, there is https://www.owasp.org/index.php/PHP_Object_Injection ...

**Comment by toolstack** [comment]
Then w.org should really deprecate it ;)
