### ISSUE TITLE
Replace scandir() with RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by ocean90** [toolstack/git-to-wp-plugin-dir-release-script#6]
Don't reinvent the wheel in https://github.com/toolstack/git-to-wp-plugin-dir-release-script/blob/master/release.php#L435. :)

Example:

``` php
$files = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator( $dir, RecursiveDirectoryIterator::SKIP_DOTS ),
    RecursiveIteratorIterator::CHILD_FIRST
);

foreach ( $files as $file ) {
    if ( $file->isDir() ) {
        rmdir( $file->getPathname() );
    } else {
        unlink( $file->getPathname() );
    }
}
```

**Comment by toolstack** [comment]
I don't like the above code for a few reasons:
1. It walks the file tree twice, once to get the files/directories and then a second time to actually delete them.
2. It has to store all the files/directories in memory.
3. It looks like it has a performance penalty as per the notes on the PHP page.

Overall, I think `delete_tree()` is a better wheel in this case, so re-inventing it is fine.
