### ISSUE TITLE
Show which files are deleted and added

### ISSUE THREAD

**Issue by ocean90** [toolstack/git-to-wp-plugin-dir-release-script#7]
```
Files to add to SVN...
Files to delete from SVN...
```

These lines should show which files are actually added/deleted.

**Comment by toolstack** [comment]
The are, however if there are no files to add/delete from SVN (not update) there is no message displayed so I'll add one.

**Comment by toolstack** [comment]
Updated next release to show modified files and ensure that add/delete/modified always produce a message even when there are no files to work on.
